[package]
name = "bedtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
system_shutdown = "3.0.0"
chrono = "0.4.19"
rand = "0.8.5"
winreg = "0.10.1"